import mongoose from 'mongoose';

const ReenrollmentSchema = new mongoose.Schema({
    financial_name: String,
    financial_birth_date: Date,
    financial_nacionality: String,
    financial_civil_state: String,
    financial_profission: String,
    financial_cpf: String,
    financial_rg: String,
    financial_address_street: String,
    financial_address_number: String,
    financial_address_complement: String,
    financial_address_neighborhood: String,
    financial_address_city: String,
    financial_address_cep: String,
    financial_residencial_phone: String,
    financial_commercial_phone: String,
    financial_personal_phone: String,
    financial_education_level: String,
    financial_workplace: String,
    financial_monthly_income: Number,
    financial_income_tax: Boolean,
    financial_email: String,

    supportive_name: String,
    supportive_birth_date: Date,
    supportive_nacionality: String,
    supportive_civil_state: String,
    supportive_profission: String,
    supportive_cpf: String,
    supportive_rg: String,
    supportive_address_street: String,
    supportive_address_number: String,
    supportive_address_complement: String,
    supportive_address_neighborhood: String,
    supportive_address_city: String,
    supportive_address_cep: String,
    supportive_residencial_phone: String,
    supportive_commercial_phone: String,
    supportive_personal_phone: String,
    supportive_education_level: String,
    supportive_workplace: String,
    supportive_monthly_income: Number,
    supportive_email: String,

    student_name: String,
    student_father_name: String,
    student_mother_name: String,
    student_birth_date: Date,
    student_nacionality: String,
    student_birth_city: String,
    student_birth_state: String,
    student_gender: String,
    student_race: String,
    student_ease_relating: Boolean,
    student_origin_school: String,
    student_healt_plan: String,
    student_food_alergy: String,
    student_medication_alergy: String,
    student_health_problem: String,
    student_special_necessities: String,

    grade_name: String,
});

export default ReenrollmentSchema;
